### ISSUE TITLE
[BUG] clippy does not work on 1.75.0 toolchain

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#1446]
## Bug Report
The rust 1.75.0 toolchain's clippy results in the following error:
```
% cargo +risc0 clippy --target riscv32im-risc0-zkvm-elf
error: malformed output when learning about crate-type bin information
command was: `/Users/erik/.rustup/toolchains/risc0/bin/clippy-driver /Users/erik/.rustup/toolchains/risc0/bin/rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg`
(no output received)
```

## Steps to Reproduce
1. download 1.75.0 toolchain via `cargo risczero install --version v2024-01-31.1`
2. run `cargo +risc0 clippy --target riscv32im-risc0-zkvm-elf` on the guest crate

## Expected behavior
clippy should run by building/analyzing the code within the crate

## Your Environment
- risc0-zkvm version: v0.20.1
- Rust version: host 1.74.0 guest: 1.75.0
- Platform/OS: mac

## Additional context
To debug I've been using `CARGO_LOG=trace`

**Comment by nazar-pc** [comment]
I'm getting similar errors with clippy on newer nightly too:
```
app: error[E0463]: can't find crate for `core`
app:   |
app:   = note: the `riscv32im-risc0-zkvm-elf` target may not be installed
app:   = help: consider downloading the target with `rustup target add riscv32im-risc0-zkvm-elf`
app:   = help: consider building the standard library from source with `cargo build -Zbuild-std`
app: 
app: error[E0463]: can't find crate for `compiler_builtins`
app: 
app: error[E0463]: can't find crate for `alloc`
app:   --> src/main.rs:23:1
app:    |
app: 23 | extern crate alloc;
app:    | ^^^^^^^^^^^^^^^^^^^ can't find crate
app: 
app: error[E0786]: found invalid metadata files for crate `risc0_zkvm`
app:  --> src/main.rs:5:5
app:   |
app: 5 | use risc0_zkvm::guest::env;
app:   |     ^^^^^^^^^^
app:   |
app:   = note: invalid metadata version found: /home/nazar-pc/.cache/cargo/target/riscv-guest/riscv32im-risc0-zkvm-elf/release/deps/librisc0_zkvm-ccec01af462e87cf.rlib
```

Currently on:
```
rustc 1.78.0-nightly (c475e2303 2024-02-28)
```

**Comment by flaub** [comment]
Does this work on latest toolchain?

**Comment by nazar-pc** [comment]
`cargo clippy` still doesn't work on `1.0.1`:
```
aes_verify: error[E0463]: can't find crate for `core`
aes_verify:   |
aes_verify:   = note: the `riscv32im-risc0-zkvm-elf` target may not be installed
aes_verify:   = help: consider downloading the target with `rustup target add riscv32im-risc0-zkvm-elf`
aes_verify:   = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

`cargo +risc0 clippy` doesn't work either because it is linked to OpenSSL 1.1 for some reason :man_shrugging:, which I don't have on Ubuntu 24.04:
```
/home/nazar-pc/.rustup/toolchains/risc0/bin/cargo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by wraitii** [comment]
The issue is the `RUSTC_WORKSPACE_WRAPPER` env variable that `clippy` sets, which interferes.

You can fix it by just temporarily resetting that variable in the build script.
